name = "serverless-social-bot"
main = "worker.js"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 */2 * * *"]  # Run every 2 hours

[build]
command = "npm install"

[vars]
DEBUG_MODE = "true"  # change this to start publishing live
DEBUG_LEVEL = "verbose"
MARKOV_STATE_SIZE = "2"
MARKOV_MAX_TRIES = "100"
MARKOV_MIN_CHARS = "100"
MARKOV_MAX_CHARS = "280"
BLUESKY_API_URL = "https://bsky.social"  # No trailing slash
MASTODON_API_URL = "https://hachyderm.io"  # No trailing slash

[env.dev]
vars = { DEBUG_MODE = "true", DEBUG_LEVEL = "verbose" }

# Secrets that should be set via wrangler
# wrangler secret put BLUESKY_USERNAME
# wrangler secret put BLUESKY_PASSWORD
# wrangler secret put MASTODON_ACCESS_TOKEN
# wrangler secret put BLUESKY_SOURCE_ACCOUNTS
# wrangler secret put MASTODON_SOURCE_ACCOUNTS
# wrangler secret put EXCLUDED_WORDS

# Development secrets - these will be loaded from .dev.vars
# Create a .dev.vars file with these secrets for local development:
# BLUESKY_USERNAME
# BLUESKY_PASSWORD
# MASTODON_ACCESS_TOKEN
# BLUESKY_SOURCE_ACCOUNTS
# MASTODON_SOURCE_ACCOUNTS
# EXCLUDED_WORDS

[observability.logs]
enabled = true
