name = "serverless-social-bot"
main = "worker.js"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat_v2"]

[triggers]
crons = ["0 */2 * * *"]  # Run every 2 hours

[build]
command = "npm install"

[vars]
DEBUG_MODE = "false"  # change this to start publishing live
DEBUG_LEVEL = "verbose"
MARKOV_STATE_SIZE = "2"
MARKOV_MAX_TRIES = "100"
MARKOV_MIN_CHARS = "100"
MARKOV_MAX_CHARS = "280"
MASTODON_API_URL = "https://hachyderm.io"
BLUESKY_API_URL = "https://bsky.social"

[[kv_namespaces]]
binding = "SOURCE_TWEETS"   # KV namespace for storing source tweets
id = "8211e674157b47f5a91c8450f2be2353"
preview_id = "7339cc8b393c4dbdb51562eb12c3962c"  # For local development

[[kv_namespaces]]
binding = "POSTS_KV"   # KV namespace for storing posts
id = "31e47afe3e4a478b98e359359abae77f"
preview_id = "98838cc54167459cb52a98c03e5b47b4"  # For local development

[env.dev]
vars = { DEBUG_MODE = "false", DEBUG_LEVEL = "verbose" }

# Secrets that should be set via wrangler
# wrangler secret put MASTODON_ACCESS_TOKEN
# wrangler secret put BLUESKY_USERNAME
# wrangler secret put BLUESKY_PASSWORD
# wrangler secret put BLUESKY_SOURCE_ACCOUNTS
# wrangler secret put MASTODON_SOURCE_ACCOUNTS
# wrangler secret put EXCLUDED_WORDS

# Development secrets - these will be loaded from .dev.vars
# Create a .dev.vars file with these secrets for local development:
# BLUESKY_USERNAME
# BLUESKY_PASSWORD
# MASTODON_ACCESS_TOKEN
# BLUESKY_SOURCE_ACCOUNTS
# MASTODON_SOURCE_ACCOUNTS
# EXCLUDED_WORDS

[observability.logs]
enabled = true
